export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';

export const ORDER_ASSIGN_DRIVER_REQUEST = 'ORDER_ASSIGN_DRIVER_REQUEST';
export const ORDER_ASSIGN_DRIVER_SUCCESS = 'ORDER_ASSIGN_DRIVER_SUCCESS';
export const ORDER_ASSIGN_DRIVER_FAIL = 'ORDER_ASSIGN_DRIVER_FAIL';

export const ORDER_DRIVER_REQUEST = 'ORDER_DRIVER_REQUEST';
export const ORDER_DRIVER_SUCCESS = 'ORDER_DRIVER_SUCCESS';
export const ORDER_DRIVER_FAIL = 'ORDER_DRIVER_FAIL';

export const ORDER_MARK_DRIVER_DELIVERED_REQUEST =
  'ORDER_MARK_DRIVER_DELIVERED_REQUEST';
export const ORDER_MARK_DRIVER_DELIVERED_SUCCESS =
  'ORDER_MARK_DRIVER_DELIVERED_SUCCESS';
export const ORDER_MARK_DRIVER_DELIVERED_FAIL =
  'ORDER_MARK_DRIVER_DELIVERED_FAIL';

export const ORDER_MARK_DRIVER_FAILED_REQUEST =
  'ORDER_MARK_DRIVER_FAILED_REQUEST';
export const ORDER_MARK_DRIVER_FAILED_SUCCESS =
  'ORDER_MARK_DRIVER_FAILED_SUCCESS';
export const ORDER_MARK_DRIVER_FAILED_FAIL = 'ORDER_MARK_DRIVER_FAILED_FAIL';
