export const PROPERTY_LIST_REQUEST = 'PROPERTY_LIST_REQUEST';
export const PROPERTY_LIST_SUCCESS = 'PROPERTY_LIST_SUCCESS';
export const PROPERTY_LIST_FAIL = 'PROPERTY_LIST_FAIL';

export const CREATE_PROPERTY_REQUEST = 'CREATE_PROPERTY_REQUEST';
export const CREATE_PROPERTY_SUCCESS = 'CREATE_PROPERTY_SUCCESS';
export const CREATE_PROPERTY_FAIL = 'CREATE_PROPERTY_FAIL';
export const CREATE_PROPERTY_RESET = 'CREATE_PROPERTY_RESET';
